# Generated by Django 4.2.6 on 2023-11-15 06:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disccount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('description', models.TextField()),
            ],
        ),
    ]
